aboutSuccess:
  metas:
    title: 'About - Kanji Koohii'
    robots: 'noindex,follow'

learnmoreSuccess:
  metas:
    title: 'Learn more - Kanji Koohii'

supportSuccess:
  metas:
    title: 'Support Kanji Koohii'
    robots: 'noindex,follow'
