indexSuccess:
  metas:
    title: 'Spaced Repetition - Kanji Koohii'
  javascripts:
    - src/entry-review.ts

reviewSuccess:
  metas:
    title: 'Flashcard Review'
  javascripts:
    - src/entry-review.ts

summarySuccess:
  metas:
    title: 'Review Summary'

vocabSuccess:
  metas:
    title: 'Vocab Shuffle Review'
