customSuccess:
  metas:
    title: "Custom Kanji Review - Kanji Koohii"

indexSuccess:
  metas:
    title: "Spaced Repetition - Kanji Koohii"
  javascripts:
    - src/entry-review.ts

reviewSuccess:
  metas:
    title: "Flashcard Review - Kanji Koohii"
  javascripts:
    - src/entry-review.ts

summarySuccess:
  metas:
    title: "Review Summary - Kanji Koohii"

vocabSuccess:
  metas:
    title: "Vocab Shuffle - Kanji Koohii"
