index:
  metas:
    title: "Study: Introduction"

edit:
  metas:
    title: "Index"

failedlist:
  metas:
    title: "Study: Failed Kanji List"

mystories:
  metas:
    title: "Study: My Stories List"

all:
  javascripts:
    - src/entry-study.ts
