indexGuest:
  metas:
    title: "Kanji Koohii"
  javascripts:
    - src/entry-landing.ts

indexMember:
  javascripts:
    - src/entry-home.ts

loginSuccess:
  metas:
    title: "Sign In - Kanji Koohii"
    robots: "noindex, follow"

contactSuccess:
  metas:
    title: "Contact - Kanji Koohii"
    robots: "noindex, follow"

memberslistSuccess:
  metas:
    title: "Who's reviewing? - Kanji Koohii"
    robots: "noindex, nofollow"
